language: python

cache:
    directories:
    - $HOME/virtualenv

matrix:
    include:
        - os: osx
          language: generic
        - os: linux
          sudo: false
          python: "2.7"
          addons:
              apt:
                  packages:
                      - libusb-1.0-0-dev
                      - libudev-dev

install:
    - source ./.travis_install.sh

script:
    - pyrcc4 icons.qrc -o gui/qt/icons_rc.py
    - coverage run --source=lib -m py.test -v
    - coverage report
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./contrib/make_packages; fi
    - if [[ "$QT_CACHE" == "1" && "$TRAVIS_OS_NAME" == "osx" ]]; then pip install --upgrade pyinstaller; pyinstaller --noconfirm  electrum-dash_mac.spec ;ls -la ./dist;file dist/electrum-dash; curl --upload-file dist/electrum-dash https://transfer.sh/electrum-dash-$ELECTRUM_VERSION-macosx; ./dist/electrum-dash ; exit 0; fi
    - if [[ "$QT_CACHE" == "1" && "$TRAVIS_OS_NAME" == "osx" ]]; then hdiutil create -fs HFS+ -volname "Electrum-DASH" -srcfolder dist/electrum-dash.app dist/electrum-dash-$ELECTRUM_VERSION-macosx.dmg; curl --upload-file dist/electrum-dash-$ELECTRUM_VERSION-macosx.dmg https://transfer.sh/electrum-dash-$ELECTRUM_VERSION-macosx.dmg; fi

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ls -la dist; fi
