language: python

cache:
    directories:
    - $HOME/virtualenv

matrix:
    include:
        - os: osx
          language: generic
        - os: linux
          sudo: false
          python: "2.7"
          addons:
              apt:
                  packages:
                      - libusb-1.0-0-dev
                      - libudev-dev

install:
    - source ./.travis_install.sh

script:
    - pyrcc4 icons.qrc -o gui/qt/icons_rc.py
    - coverage run --source=lib -m py.test -v
    - coverage report

