language: python

cache:
    directories:
    - $HOME/virtualenv

matrix:
    include:
        - os: osx
          language: generic
        - os: linux
          sudo: false
          python: "2.7"
          addons:
              apt:
                  packages:
                      - libusb-1.0-0-dev
                      - libudev-dev

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install protobuf zbar; fi
    - source ./.travis_install.sh

script:
    - pyrcc4 icons.qrc -o gui/qt/icons_rc.py
    - echo coverage run --source=lib -m py.test -v
    - echo coverage report
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pyinstaller --noconfirm  --distpath ./pyinstaller-dist electrum-dash_linux.spec; cd pyinstaller-dist; mv Electrum-DASH.bin Electrum-DASH-$ELECTRUM_VERSION.bin ; ls -la; file Electrum-DASH-$ELECTRUM_VERSION.bin  ; curl --upload-file Electrum-DASH-$ELECTRUM_VERSION.bin https://transfer.sh/Electrum-DASH-$ELECTRUM_VERSION.bin ;./Electrum-DASH-$ELECTRUM_VERSION.bin ;cd ..; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./contrib/make_packages; ls -la ./dist; fi
    - if [[ "$QT_CACHE" == "1" && "$TRAVIS_OS_NAME" == "osx" ]]; then file packages/x11_hash.so;pyinstaller --noconfirm  electrum-dash_mac.spec ;ls -la ./dist; ls -la ./packages;fi
    - if [[ "$QT_CACHE" == "1" && "$TRAVIS_OS_NAME" == "osx" ]]; then hdiutil create -fs HFS+ -volname "Electrum-DASH" -srcfolder dist/electrum-dash.app dist/electrum-dash-$ELECTRUM_VERSION.dmg; fi

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ls -la dist; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl --upload-file dist/electrum-dash.bin https://transfer.sh/Electrum-DASH-$ELECTRUM_VERSION.bin;echo;  curl --upload-file dist/electrum-dash-$ELECTRUM_VERSION.dmg https://transfer.sh/Electrum-DASH-$ELECTRUM_VERSION.dmg; fi
